# .goreleaser.yml
project_name: docker-machine-nutanix

builds:
  - goos:
      - linux
    goarch:
      - amd64

archives:
  - name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "{{ .ProjectName }}_v{{ .Version }}_checksums.txt"
